### ISSUE TITLE
Even Fibonacci: wrong result of sum

### ISSUE THREAD

**Issue by rakvium** [domenic99/trainee-rep#5]
Sum for Fibonacci numbers less than `4_000_000` cannot be less than `2_000_000`.
`EvenFibonacci.new.sum`
Expected Result: `4613732`
Actual Result: `1762285`

**Comment by domenic99** [comment]
@rakvium check out my fix https://github.com/domenic99/trainee-rep/blob/first-task/Euler/even_fibonacci.rb

**Comment by rakvium** [comment]
Done.
