### ISSUE TITLE
Euler: palindrome

### ISSUE THREAD

**Issue by rakvium** [domenic99/trainee-rep#6]
Iterating in reverse doesn't find the largest x*y, it finds the palindrome with the largest x. There's a larger answer than 580085; it has a smaller x but a larger y.

Expected Result: `906609`
Actual Result: `580085`

**Comment by domenic99** [comment]
@rakvium check commit with fix ( but with one error in rubocop)
https://github.com/domenic99/trainee-rep/blob/first-task/Euler/palindrome.rb

**Comment by rakvium** [comment]
@domenic99 you can fix rubocop issue by replacing `check` with `@check` and removing `check` assignment to `'0'`.

**Comment by domenic99** [comment]
Thx for helping with fix :)
https://github.com/domenic99/trainee-rep/blob/first-task/Euler/palindrome.rb
